simple_blogs/config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'articles#index', as: :tag
  get 'announcements/:id/hide', to: 'announcements#hide', as: :hide_announcement

  root to: 'articles#index'
  resources :articles  do
    resources :comments
  end

  resources :users

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :password_resets

end

simple_blogs/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article, touch: true
end

simple_blogs/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.save
    redirect_to @article
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @article = Article.find(params[:article_id])
    if @comment.update(comment_params)
      redirect_to @article
    end
  end

  def destroy
    @comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :commenter)
  end
end

simple_blogs/app/views/comments/_comment.html.erb

<%= div_for comment do %>
  <p><strong><%= comment.commenter %> says</strong></p>
  <%= simple_format comment.content %>

	<%= link_to "Edit", edit_article_comment_path(comment.article, comment) %> |
	<%= link_to "Delete", [comment.article, comment], :method => :delete, :data => { :confirm => "Are you sure?"} %>
<br>
<% end %>


simple_blogs/app/views/comments/_form.html.erb
<%= form_for([@article, Comment.new]) do |f| %>
<p>
<%= f.label :commenter %><br>
<%= f.text_field :commenter %>
</p>
<p>
	<%= f.label :content %><br>
	<%= f.text_area :content %>
</p>
<br />
<%= f.submit "Comment" %>
<% end %>

simple_blogs/app/views/comments/edit.html.erb
<h2> Edit Comment </h2>

<%= form_for([@article, @comment]) do |f| %>
	<%= f.text_field :content %>
  <%= f.submit :Submit %>
<% end %>