simple_blogs/config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'articles#index', as: :tag
  get 'announcements/:id/hide', to: 'announcements#hide', as: :hide_announcement

  root to: 'articles#index'
  resources :articles  do
    resources :comments
  end

  resources :users

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :password_resets

end

simple_blogs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Blogs Apps -- <%= content_for?(:title) ? yield(:title) :  "Place for Blogs" %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% Announcement.current(cookies.signed[:hidden_announcement_ids]).each do |announcement| %>
		<%= div_for announcement do %>
			<%= announcement.message %>
			<%= link_to "hide announcement", hide_announcement_path(announcement) %>
		<% end %>
	<% end %>
	<div id="container">
		<div id="user_header">
				<%= link_to "New Article", new_article_path %>
			<% if current_user %>
					Logged in as <%= current_user.email %>.
				<%= link_to "Log Out", logout_path %>
			<% else %>
					<%= link_to "Sign Up", signup_path %> or
				<%= link_to "Log In", login_path %>
			<% end %>
		</div>

		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

<%= yield %>
	</div>

</body>
</html>